### ISSUE TITLE
Communication timeout causing node red crashes

### ISSUE THREAD

**Issue by mariusss21** [plcpeople/nodepccc#24]
Hello,

first of all, thanks for your great library.

I'm using your library to communicate with a CompactLogix L33ERM and I'm getting this error in case of communication failure.

`26 May 12:50:27 - TypeError: Cannot read property 'length' of undefined
    at processSLCWriteItem (/usr/lib/node_modules/node-red-contrib-ccc/node_modules/nodepccc/nodePCCC.js:1572:13)
    at NodePCCC.writeResponse (/usr/lib/node_modules/node-red-contrib-pccc/node_modules/nodepccc/nodePCCC.js:1270:17)
    at NodePCCC.packetTimeout (/usr/lib/node_modules/node-red-contrib-pccc/node_modules/nodepccc/nodePCCC.js:232:8)
    at Timeout._onTimeout (/usr/lib/node_modules/node-red-contrib-pccc/node_modules/nodepccc/nodePCCC.js:1023:24)
    at ontimeout (timers.js:393:15)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5) `

**Comment by plcpeople** [comment]
This was obviously a bug - please let me know if you still see issues following the attempted fix.
