### ISSUE TITLE
0.1.10 crash

### ISSUE THREAD

**Issue by srebling** [plcpeople/nodepccc#28]
Getting this error with new commit. 

node-pccc/node_modules/nodepccc/nodePCCC.js:381
NodePCCC.prototype.findItem = function(useraddr) {
^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/stevenebling/node-proj/node-pccc/app.js:1:78)

**Comment by plcpeople** [comment]
Sorry, should be good now with latest commit and publish.
